#             SIMBU DataScientist

## NUMPY

In [239]:
import numpy as np

In [240]:
a = np.array 

In [241]:
print(a)

<built-in function array>


In [244]:
my_arr=np.arange(1000000)

In [245]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [246]:
my_list=list(range(1000000))

In [247]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [14]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 88 ms


In [248]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 2.82 s


#### The Numpy ndarray:A multidimensional Array Object

In [253]:
data=np.random.randn(2,3)

In [255]:
data

array([[-2.59627433,  0.085757  ,  0.73819296],
       [-0.18079671, -0.30466836,  2.04645995]])

In [256]:
data*10

array([[-25.96274333,   0.85757   ,   7.38192957],
       [ -1.80796708,  -3.04668362,  20.4645995 ]])

In [257]:
data+data

array([[-5.19254867,  0.171514  ,  1.47638591],
       [-0.36159342, -0.60933672,  4.0929199 ]])

In [258]:
data.shape

(2, 3)

In [259]:
data.dtype

dtype('float64')

##### Creating ndarray

In [260]:
data1=[6,7.5,8,0,1]

In [261]:
arr1=np.array(data1)

In [262]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [263]:
arr1.dtype

dtype('float64')

In [264]:
data2=[[1,2,3,4],[5,6,7,8]]

In [265]:
arr2=np.array(data2)

In [267]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [268]:
arr2.ndim

2

In [269]:
arr2.shape

(2, 4)

In [270]:
arr1.dtype

dtype('float64')

In [271]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [272]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [273]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [274]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [275]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [276]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [281]:
np.empty(25)

array([4.67296746e-307, 1.69121096e-306, 2.78145267e-307, 1.89144350e-307,
       1.33511018e-306, 1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
       9.34609790e-307, 8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
       6.23061763e-307, 8.90104239e-307, 6.89804132e-307, 1.22387465e-307,
       1.42418172e-306, 2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
       8.90111708e-307, 3.22643519e-307, 9.79103798e-307, 2.46155235e-312,
       0.00000000e+000])

#### Data Types for ndarray

In [288]:
arr1=np.array([1,2,3,4],dtype=np.float64)

In [289]:
arr1

array([1., 2., 3., 4.])

In [290]:
arr1.dtype

dtype('float64')

In [291]:
arr2.dtype

dtype('int32')

In [292]:
arr=np.array([1,2,3,4,5])

In [293]:
arr.dtype

dtype('int32')

In [294]:
float_arr=arr.astype(np.float64)

In [295]:
float_arr.dtype

dtype('float64')

In [296]:
arr=np.array([3.7,-2.6])

In [299]:
arr.dtype

dtype('float64')

In [298]:
arr

array([ 3.7, -2.6])

In [49]:
numeric_string=np.array(['1.25','-9.6','42'])

In [50]:
numeric_string.dtype

dtype('<U4')

In [51]:
a=numeric_string.astype(float)

In [52]:
a.dtype

dtype('float64')

In [53]:
int_array=np.arange(10)

In [54]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
calibers=np.array([.22,.270,.357],dtype=np.float64)

In [56]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
empty_uint32=np.empty(8,dtype='u4')

In [58]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

#### Arithmetic With Numpy Array

In [59]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [60]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [61]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [62]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

* arithmetic operation with Scalar propagation the scalar argument to each element in array

In [63]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [64]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [65]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])

In [66]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

##### Basic Indexing and Slicing

In [67]:
arr=np.arange(10)

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[5]

5

In [70]:
arr[5:8]

array([5, 6, 7])

In [71]:
arr[5:8]=12

In [72]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [73]:
arr_slice=arr[5:8]

In [74]:
arr_slice

array([12, 12, 12])

In [75]:
arr_slice[1]=12345

In [76]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [77]:
arr_slice[:]=64

In [78]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [79]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [80]:
arr2d[2]

array([7, 8, 9])

In [81]:
arr2d[0][2]

3

In [82]:
arr2d[0,2]

3

#### 3D

In [83]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [84]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [85]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
old_values=arr3d[0].copy()

In [87]:
arr3d[0]=42

In [88]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [89]:
arr3d[0]=old_values

In [90]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [91]:
arr3d[1,0]

array([7, 8, 9])

In [92]:
x=arr3d[1]

In [93]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [94]:
x[0]

array([7, 8, 9])

In [95]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [96]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [97]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [100]:
arr2d[1,:2]

array([4, 5])

In [101]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [102]:
arr2d[:2,1:]=0

In [103]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### Boolean Indexing

In [104]:
names=np.array(['simbu','Aashik','karthi','arun','priya','jai','chandra'])

In [105]:
data=np.random.randn(7,4)

In [106]:
data

array([[ 0.40990488,  0.33679568, -0.54473999,  0.0883672 ],
       [-0.05231091, -0.0739147 ,  0.33879963, -1.5839253 ],
       [-0.5019481 , -0.3680917 ,  0.88904048, -0.76139079],
       [-0.87356066,  1.82130586, -0.11355815, -0.09379689],
       [-0.88130997, -0.87313535, -0.86653076, -0.32588485],
       [ 0.6210804 , -0.77294289, -0.45057535, -1.40831385],
       [-1.34022233,  1.34806674,  0.27369692, -0.1245132 ]])

In [107]:
names=='simbu'

array([ True, False, False, False, False, False, False])

In [108]:
data[names=='simbu']

array([[ 0.40990488,  0.33679568, -0.54473999,  0.0883672 ]])

In [109]:
data[names=='simbu',2:]

array([[-0.54473999,  0.0883672 ]])

In [110]:
data[~(names=='simbu')] # not equal

array([[-0.05231091, -0.0739147 ,  0.33879963, -1.5839253 ],
       [-0.5019481 , -0.3680917 ,  0.88904048, -0.76139079],
       [-0.87356066,  1.82130586, -0.11355815, -0.09379689],
       [-0.88130997, -0.87313535, -0.86653076, -0.32588485],
       [ 0.6210804 , -0.77294289, -0.45057535, -1.40831385],
       [-1.34022233,  1.34806674,  0.27369692, -0.1245132 ]])

In [111]:
cond=names=='simbu'

In [112]:
cond

array([ True, False, False, False, False, False, False])

In [113]:
data[~cond]

array([[-0.05231091, -0.0739147 ,  0.33879963, -1.5839253 ],
       [-0.5019481 , -0.3680917 ,  0.88904048, -0.76139079],
       [-0.87356066,  1.82130586, -0.11355815, -0.09379689],
       [-0.88130997, -0.87313535, -0.86653076, -0.32588485],
       [ 0.6210804 , -0.77294289, -0.45057535, -1.40831385],
       [-1.34022233,  1.34806674,  0.27369692, -0.1245132 ]])

In [114]:
mask=(names=='simbu')|(names=='Aashik')

In [115]:
mask

array([ True,  True, False, False, False, False, False])

In [116]:
data[mask]

array([[ 0.40990488,  0.33679568, -0.54473999,  0.0883672 ],
       [-0.05231091, -0.0739147 ,  0.33879963, -1.5839253 ]])

In [117]:
data[data<0]=0

In [118]:
data

array([[0.40990488, 0.33679568, 0.        , 0.0883672 ],
       [0.        , 0.        , 0.33879963, 0.        ],
       [0.        , 0.        , 0.88904048, 0.        ],
       [0.        , 1.82130586, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.6210804 , 0.        , 0.        , 0.        ],
       [0.        , 1.34806674, 0.27369692, 0.        ]])

In [119]:
data[names!='priya']=7

In [120]:
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### Fancy Indexing

In [121]:
arr=np.empty((8,4))

In [122]:
for i in range(8):
    arr[i]=i

In [123]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [124]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [125]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [126]:
arr=np.arange(32).reshape((8,4))

In [127]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [128]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

#### Transposing Arrays and Swapping Axes

In [129]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [130]:
arr=np.random.randn(6,3)

In [131]:
arr

array([[ 0.32419442, -0.83396491, -0.03504769],
       [-2.57804439,  0.47401471,  1.04311774],
       [ 0.15373312,  0.55507651, -0.42651642],
       [-1.73865199, -0.47640055, -0.83850406],
       [ 1.73359141, -0.39952694, -0.80896021],
       [-1.18861683,  0.10700596,  0.95111499]])

In [132]:
np.dot(arr.T,arr)

array([[14.21610867, -1.39857488, -3.84118681],
       [-1.39857488,  1.62632687,  1.11137262],
       [-3.84118681,  1.11137262,  3.53336463]])

In [133]:
arr=np.arange(16).reshape((2,2,4))

In [134]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [135]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [136]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### NumPy String Functions

In [137]:
np.char.add(['welcome','Hi'], [' to simbu', ' read python'] )

array(['welcome to simbu', 'Hi read python'], dtype='<U19')

In [138]:
np.char.multiply("hello ",3)

array('hello hello hello ', dtype='<U18')

In [139]:
np.char.center("simbu", 20, '*')

array('*******simbu********', dtype='<U20')

In [140]:
np.char.capitalize("welcome to silambarasan")

array('Welcome to silambarasan', dtype='<U23')

In [141]:
np.char.title("welcome to silambarasan")

array('Welcome To Silambarasan', dtype='<U23')

In [142]:
np.char.lower("WELCOME TO SILAMBARASAN")

array('welcome to silambarasan', dtype='<U23')

In [143]:
np.char.upper("Welcome To Silambarasan")

array('WELCOME TO SILAMBARASAN', dtype='<U23')

In [144]:
np.char.split("Welcome To Silambarasan")

array(list(['Welcome', 'To', 'Silambarasan']), dtype=object)

In [145]:
np.char.splitlines("Welcome\nTo\nSilambarasan")

array(list(['Welcome', 'To', 'Silambarasan']), dtype=object)

In [146]:
str = "     welcome to Silambarasan     "    
np.char.strip(str)

array('welcome to Silambarasan', dtype='<U33')

In [147]:
np.char.join(':','HM')

array('H:M', dtype='<U3')

In [148]:
str = "Welcome to silambarasan"  

print(np.char.replace(str, "Welcome to","www."))  

www. silambarasan


In [149]:
enstr = np.char.encode("welcome to simbu", 'cp500')  
dstr =np.char.decode(enstr, 'cp500')  
print(enstr)  
print(dstr)  

b'\xa6\x85\x93\x83\x96\x94\x85@\xa3\x96@\xa2\x89\x94\x82\xa4'
welcome to simbu


### NumPy Mathematical Functions

In [150]:
arr = np.array([0, 30, 60, 90, 120, 150, 180])  
print("\nThe sin value of the angles",end = " ")  
print(np.sin(arr))  
print("\nThe cosine value of the angles",end = " ")  
print(np.cos(arr))  
print("\nThe tangent value of the angles",end = " ")  
print(np.tan(arr)) 


The sin value of the angles [ 0.         -0.98803162 -0.30481062  0.89399666  0.58061118 -0.71487643
 -0.80115264]

The cosine value of the angles [ 1.          0.15425145 -0.95241298 -0.44807362  0.81418097  0.69925081
 -0.59846007]

The tangent value of the angles [ 0.         -6.4053312   0.32004039 -1.99520041  0.71312301 -1.02234624
  1.33869021]


In [151]:
 cosec = np.arcsin(np.sin(arr))  

In [152]:
cosec

array([ 0.        , -1.41592654, -0.30973958,  1.10618695,  0.61947916,
       -0.79644737, -0.92921875])

In [153]:
sec = np.arccos(np.cos(arr)) 

In [154]:
sec

array([0.        , 1.41592654, 2.83185307, 2.0354057 , 0.61947916,
       0.79644737, 2.21237391])

In [155]:
np.degrees(sec)

array([  0.        ,  81.12661461, 162.25322922, 116.62015618,
        35.49354157,  45.63307304, 126.75968765])

In [156]:
print("\nprinting the tan values of different angles")  
tanval = np.tan(arr*np.pi/180)  
  
print(tanval)  
print("printing the inverse of the tan")  
cot = np.arctan(tanval)  
print(cot)  
  
print("\nprinting the values in degrees")  
print(np.degrees(cot))  


printing the tan values of different angles
[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]
printing the inverse of the tan
[ 0.00000000e+00  5.23598776e-01  1.04719755e+00  1.57079633e+00
 -1.04719755e+00 -5.23598776e-01 -1.22464680e-16]

printing the values in degrees
[ 0.0000000e+00  3.0000000e+01  6.0000000e+01  9.0000000e+01
 -6.0000000e+01 -3.0000000e+01 -7.0167093e-15]


In [157]:
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(arr)  
print("Array values rounded off to 2 decimal position",np.around(arr, 2))  
print("Array values rounded off to -1 decimal position",np.around(arr, -1))  

[ 12.202   90.2312 123.02    23.202 ]
Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


In [158]:
np.floor(arr)

array([ 12.,  90., 123.,  23.])

In [159]:
np.ceil(arr)

array([ 13.,  91., 124.,  24.])

In [160]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  

In [161]:
print("\nThe minimum element among the array:",np.amin(a))  
print("The maximum element among the array:",np.amax(a))  
  
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("The maximum element among the rows of array",np.amax(a,0))  
  
print("\nThe minimum element among the columns of array",np.amin(a,1))  
print("The maximum element among the columns of array",np.amax(a,1))  


The minimum element among the array: 2
The maximum element among the array: 80

The minimum element among the rows of array [ 2 10 10]
The maximum element among the rows of array [80 43 31]

The minimum element among the columns of array [ 2 31 10]
The maximum element among the columns of array [20 80 43]


In [162]:
#Range of values (maximum - minimum) along an axis.
print("\nptp value along axis 1:",np.ptp(a,1))  
  
print("ptp value along axis 0:",np.ptp(a,0))  


ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


In [163]:
print("\nPercentile along axis 0",np.percentile(a, 10,0))  
  
print("Percentile along axis 1",np.percentile(a, 10, 1))  


Percentile along axis 0 [ 6.  16.6 12. ]
Percentile along axis 1 [ 3.6 33.4 12.4]


In [164]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
  
print("Array:\n",a)  
  
print("\nMedian of array along axis 0:",np.median(a,0))  
print("Mean of array along axis 0:",np.mean(a,0))  
print("Average of array along axis 1:",np.average(a,1))  

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]
Mean of array along axis 0: [4. 5. 6.]
Average of array along axis 1: [2. 5. 8.]


In [165]:
arr=np.arange(10)

In [166]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [168]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [169]:
x=np.random.randn(8)

In [170]:
x

array([-0.01905356,  1.37186547, -2.04338855,  0.57425051, -0.8669694 ,
        0.52276634,  0.09831331,  0.31576798])

In [171]:
y=np.random.randn(8)

In [172]:
y

array([ 0.30663192, -1.6600432 ,  0.73064868,  1.11230566,  0.03726153,
        1.35507276, -0.57869883,  1.36005937])

In [173]:
np.maximum(x,y)

array([0.30663192, 1.37186547, 0.73064868, 1.11230566, 0.03726153,
       1.35507276, 0.09831331, 1.36005937])

In [174]:
arr=np.random.randn(7)*5

In [175]:
arr

array([-0.12172319, -2.07321122, -4.5365914 ,  2.54520293, -2.97145447,
        4.22924301, -7.75680991])

In [176]:
remainder,whole_part=np.modf(arr)

In [177]:
remainder

array([-0.12172319, -0.07321122, -0.5365914 ,  0.54520293, -0.97145447,
        0.22924301, -0.75680991])

In [178]:
whole_part

array([-0., -2., -4.,  2., -2.,  4., -7.])

In [179]:
arr

array([-0.12172319, -2.07321122, -4.5365914 ,  2.54520293, -2.97145447,
        4.22924301, -7.75680991])

In [180]:
np.sqrt(arr)

C:\Users\JAIKUMAR\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan, 1.59536921,        nan,
       2.05651234,        nan])

In [181]:
np.abs(arr)#absolute value

array([0.12172319, 2.07321122, 4.5365914 , 2.54520293, 2.97145447,
       4.22924301, 7.75680991])

In [182]:
np.fabs(arr)# floating point

array([0.12172319, 2.07321122, 4.5365914 , 2.54520293, 2.97145447,
       4.22924301, 7.75680991])

In [183]:
np.square(arr)

array([1.48165339e-02, 4.29820475e+00, 2.05806616e+01, 6.47805796e+00,
       8.82954170e+00, 1.78864964e+01, 6.01680999e+01])

In [184]:
np.log(arr)

C:\Users\JAIKUMAR\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan, 0.93421038,        nan,
       1.44202302,        nan])

In [185]:
np.log10(arr)

C:\Users\JAIKUMAR\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan, 0.40572241,        nan,
       0.62626264,        nan])

In [186]:
np.log2(arr)

C:\Users\JAIKUMAR\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan, 1.34778069,        nan,
       2.08039946,        nan])

In [187]:
np.log1p(arr)

C:\Users\JAIKUMAR\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log1p
  """Entry point for launching an IPython kernel.


array([-0.12979346,         nan,         nan,  1.2655954 ,         nan,
        1.65426653,         nan])

In [188]:
np.sign(arr)

array([-1., -1., -1.,  1., -1.,  1., -1.])

In [189]:
np.rint(arr)

array([-0., -2., -5.,  3., -3.,  4., -8.])

In [190]:
np.modf(arr)

(array([-0.12172319, -0.07321122, -0.5365914 ,  0.54520293, -0.97145447,
         0.22924301, -0.75680991]),
 array([-0., -2., -4.,  2., -2.,  4., -7.]))

In [191]:
np.isnan(arr)

array([False, False, False, False, False, False, False])

In [192]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True])

In [193]:
np.isinf(arr)

array([False, False, False, False, False, False, False])

In [194]:
np.cos(arr)

array([ 0.99260088, -0.4815434 , -0.17489348, -0.82736875, -0.98556138,
       -0.46456734,  0.09701888])

In [195]:
np.cosh(arr)

array([1.00741742e+00, 4.03804679e+00, 4.66913497e+01, 6.41213574e+00,
       9.78575974e+00, 3.43398985e+01, 1.16871824e+03])

In [196]:
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
  
print("Sorting along the columns:")  
print(np.sort(a))  
  
print("Sorting along the rows:")  
print(np.sort(a, 0))  
  
data_type = np.dtype([('name', 'S10'),('marks',int)])  
  
arr = np.array([('Mukesh',200),('John',251)],dtype = data_type)  
  
print("Sorting data ordered by name")  
  
print(np.sort(arr,order = 'name'))  

Sorting along the columns:
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the rows:
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
Sorting data ordered by name
[(b'John', 251) (b'Mukesh', 200)]


In [197]:
a = np.array([90, 29, 89, 12])  
  
print("Original array:\n",a)  
  
sort_ind = np.argsort(a)  
  
print("Printing indices of sorted data\n",sort_ind)  
  
sort_a = a[sort_ind]  
  
print("printing sorted array")  
  
for i in sort_ind:  
    print(a[i],end = " ")  

Original array:
 [90 29 89 12]
Printing indices of sorted data
 [3 1 2 0]
printing sorted array
12 29 89 90 

In [198]:
a = np.array(['a','b','c','d','e'])  
  
b = np.array([12, 90, 380, 12, 211])  
  
ind = np.lexsort((a,b))  
  
print("printing indices of sorted data")  
  
print(ind)  
  
print("using the indices to sort the array")  
  
for i in ind:  
    print(a[i],b[i])  

printing indices of sorted data
[0 3 1 4 2]
using the indices to sort the array
a 12
d 12
b 90
e 211
c 380


In [199]:
b = np.array([12, 90, 380, 12, 211])  
  
print("printing original array",b)  
  
print("printing location of the non-zero elements")  
  
print(b.nonzero())  

printing original array [ 12  90 380  12 211]
printing location of the non-zero elements
(array([0, 1, 2, 3, 4], dtype=int64),)


In [200]:
b = np.array([12, 90, 380, 12, 211])  
  
print(np.where(b>12))  
  
c = np.array([[20, 24],[21, 23]])  
  
print(np.where(c>20))  

(array([1, 2, 4], dtype=int64),)
(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))


In [201]:
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
  
print("Original Array:\n",a)  
  
print("\nID of array a:",id(a))  
  
b = a   
  
print("\nmaking copy of the array a")  
  
print("\nID of b:",id(b))  
  
b.shape = 4,3;  
  
print("\nChanges on b also reflect to a:")  
print(a)  

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2410548812336

making copy of the array a

ID of b: 2410548812336

Changes on b also reflect to a:
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [202]:
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
  
print("Original Array:\n",a)  
  
print("\nID of array a:",id(a))  
  
b = a.view()  
  
print("\nID of b:",id(b))  
  
print("\nprinting the view b")  
print(b)  
  
b.shape = 4,3;  
  
print("\nChanges made to the view b do not reflect a")  
print("\nOriginal array \n",a)  
print("\nview\n",b)  

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2410548615648

ID of b: 2410548671312

printing the view b
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Changes made to the view b do not reflect a

Original array 
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

view
 [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [203]:
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])  
  
print("Original Array:\n",a)  
  
print("\nID of array a:",id(a))  
  
b = a.copy()  
  
print("\nID of b:",id(b))  
  
print("\nprinting the deep copy b")  
print(b)  
  
b.shape = 4,3;  
  
print("\nChanges made to the copy b do not reflect a")  
print("\nOriginal array \n",a)  
print("\nCopy\n",b)  

Original Array:
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

ID of array a: 2410461187728

ID of b: 2410547897728

printing the deep copy b
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Changes made to the copy b do not reflect a

Original array 
 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]

Copy
 [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


In [204]:
import numpy.matlib  
  
print(numpy.matlib.empty((3,3)))  

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [205]:
print(numpy.matlib.zeros((4,3)))  

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [206]:
print(numpy.matlib.ones((2,2)))  

[[1. 1.]
 [1. 1.]]


In [207]:
print(numpy.matlib.eye(n = 3, M = 3, k = 0, dtype = int))  

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [208]:
print(numpy.matlib.identity(5, dtype = int))  

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [209]:
print(numpy.matlib.rand(3,3))  

[[0.36925879 0.03981168 0.07537583]
 [0.95725894 0.37031639 0.50246802]
 [0.65003568 0.29405078 0.44738092]]


In [210]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)  

[[3400 6200]
 [ 374  712]]


In [211]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot) 

5528


In [212]:
inner = np.inner(a,b)  
print(inner)  

[[5000 5400]
 [ 470  528]]


In [213]:
mul = np.matmul(a,b)  
print(mul)  

[[3400 6200]
 [ 374  712]]


In [214]:
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a))  

-2.0000000000000004


In [215]:
a = np.array([[1,2],[3,4]])  
b = np.array([[1,2],[3,4]])  
print(np.linalg.solve(a, b))  

[[1. 0.]
 [0. 1.]]


In [216]:
a = np.array([[1,2],[3,4]])  
print("Original array:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b)  

Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [217]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result=np.multiply(array1,array2)  
print(result)  

[[[ 9 16 21]
  [24 25 24]
  [21 16  9]]]


In [218]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result=np.matmul(array1,array2)  
print(result)  

[[[ 30  24  18]
  [ 84  69  54]
  [138 114  90]]]


In [219]:
result=np.dot(array1,array2)  
print(result)  

[[[[ 30  24  18]]

  [[ 84  69  54]]

  [[138 114  90]]]]


In [220]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y))  
print(z)  

[[ 1  2]
 [ 3  4]
 [12 30]]


In [221]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
print(c)  

[10 20 30 40 50 60 70 80 90 11 21 31 42 52 62 73 83 93]


In [222]:
x=np.arange(12)  
y=np.reshape(x, (4,3))  
print('x values',x)  
print('y values',y)  

x values [ 0  1  2  3  4  5  6  7  8  9 10 11]
y values [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [223]:
a=np.array([0.4,0.5])  
b=np.sum(a)  
print(b)

0.9


In [224]:
a=np.array([0.4,0.5,0.9,6.1])  
x=np.sum(a, dtype=np.int32)  
print(x)  

6


In [225]:
a= np.arange(6).reshape((2,3))  
print(a)  
print('')
b=np.transpose(a)  
print(b)  

[[0 1 2]
 [3 4 5]]

[[0 3]
 [1 4]
 [2 5]]


In [226]:
a = np.uint32([6, 2])  
print(a)  
print('')
a_list=list(a)  
print(a_list)
print('')
type(a_list[0])  
a_tolist=a.tolist()
print('')
print(a_tolist)  
type(a_tolist[0])

[6 2]

[6, 2]


[6, 2]


int

In [227]:
from io import StringIO  
d = StringIO(u"M 21 72\nF 35 58")  
np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),'formats': ('S1', 'i4', 'f4')})  

array([(b'M', 21, 72.), (b'F', 35, 58.)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [228]:
from io import StringIO  
c = StringIO(u"1,3,2\n3,5,4")  
x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2), unpack=True)  
print(x)  
print(y)  

[1. 3.]
[2. 4.]


In [229]:
x= np.arange(12)  
y=np.clip(x, 3, 10)  
y  

array([ 3,  3,  3,  3,  4,  5,  6,  7,  8,  9, 10, 10])

In [230]:
a = np.array([[1,4,7], [2,5,8],[3,6,9]])  
b=a.flatten()  
b  

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [231]:
na, nb = (5, 3)  
a = np.linspace(1, 2, na)  
b = np.linspace(1, 2, nb)  
xa, xb = np.meshgrid(a, b)  
print(xa)
print('')

print(xb)  

[[1.   1.25 1.5  1.75 2.  ]
 [1.   1.25 1.5  1.75 2.  ]
 [1.   1.25 1.5  1.75 2.  ]]

[[1.  1.  1.  1.  1. ]
 [1.5 1.5 1.5 1.5 1.5]
 [2.  2.  2.  2.  2. ]]


In [232]:
a=np.array([[1,4,7,10],[2,5,8,11]])  
b=np.std(a)  
b  

3.391164991562634

In [233]:
arr = np.array([0, 1, 2], dtype=np.uint8)  
arr  
b=np.diff(arr)  
b  #we tried to print the value of 'b' and the difference between elements.

array([1, 1], dtype=uint8)

In [234]:
# We have imported numpy with alias name np.
# We have declared the variable 'a' and assigned the returned value of np.histogram() function.
# We have passed an array and the value of the bin in the function.
# Lastly, we tried to print the value of 'a'.
a=np.histogram([1, 5, 2], bins=[0, 1, 2, 3])  
a 

(array([0, 1, 1], dtype=int64), array([0, 1, 2, 3]))

In [235]:
x = [1, 3, 2, 5, 4]  
y = np.pad(x, (3, 2), 'constant', constant_values=(6, 4))  
y  

array([6, 6, 6, 1, 3, 2, 5, 4, 4, 4])

In [236]:
x = np.array([[1, 3, 5], [11, 35, 56]])  
y=np.ravel(x)  
y  

array([ 1,  3,  5, 11, 35, 56])